name: Test Suite Validation

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: JSON Schema Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Install dependencies
        working-directory: ./test
        run: yarn --frozen-lockfile

      - name: Run validation tests
        working-directory: ./test
        env:
          CHAINALYSIS_API_TOKEN: ${{ secrets.CHAINALYSIS_API_TOKEN }}
        run: yarn test
